### ISSUE TITLE
No longer available

### ISSUE THREAD

**Issue by Aiosa** [nfd/KeePassNFC#1]
May I hear the reason why this app was removed from google play? It was there a few months back.

**Comment by nfd** [comment]
Hi Aiosa,

Thanks for the heads up. Google removed it because I hadn't completed their family / children / whatever suitability declaration. I've now completed it, and apparently that means they'll put it back up after a review. I would assume that will take a few days, but they don't actually give a timeline.

**Comment by nfd** [comment]
It seems to be back now.
